package io.inji.verify.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    INVALID_TRANSACTION_ID("INVALID_TRANSACTION_ID","Invalid transaction ID, No requests found for given transaction ID."),
    NO_VP_SUBMISSION("NO_VP_SUBMISSION","No VP submission found for given transaction ID."),
    NO_AUTH_REQUEST("NO_AUTH_REQUEST","No Authorization request found for given request ID."),
    DCQL_QUERY_REQUIRED("dcql_query_required","dcql_query is required"),
    INVALID_REQUEST_FORMAT("invalid_request_format", "Request body JSON is invalid or cannot be parsed."),
    DCQL_CREDENTIALS_REQUIRED("dcql_query.credentials","Each DCQL credential entry must not be null."),
    DCQL_CREDENTIALS_INVALID("dcql_query.credentials","dcql_query.credentials must be a non-empty array."),
    DCQL_CREDENTIAL_ID_REQUIRED("dcql_query.credentials","Each DCQL credential entry must contain id."),
    DCQL_CREDENTIAL_ID_INVALID("dcql_query.credentials","Credential id must contain only alphanumeric characters, underscores, and hyphens."),
    DCQL_CREDENTIAL_FORMAT_REQUIRED("dcql_query.credentials","Each DCQL credential entry must contain format."),
    DCQL_CREDENTIAL_FORMAT_INVALID("dcql_query.credentials","DCQL credential format must be a valid format."),
    DCQL_META_REQUIRED("dcql_query.credentials","Each DCQL credential entry must contain meta."),
    DCQL_META_INVALID("dcql_query.credentials","DCQL meta must not contain null/blank values."),
    DCQL_META_TYPE_VALUE_INVALID_IRI("dcql_query.credentials","Each value in type_values must be a valid IRI (absolute or relative)."),
    DCQL_META_DUPLICATES("dcql_query.credentials","DCQL meta must not contain duplicate values."),
    DCQL_META_NOT_MATCHING_FORMAT("dcql_query.credentials","DCQL meta fields must match the specified credential format."),
    DCQL_CLAIM_ID_INVALID("dcql_query.credentials","Claim id must contain only alphanumeric characters, underscores, and hyphens."),
    DCQL_DUPLICATE_CLAIM_PATH("dcql_query.credentials","Duplicate claim paths are not allowed within a single credential query."),
    DCQL_CLAIM_PATH_REQUIRED("dcql_query.credentials","Each claim must contain path."),
    DCQL_CLAIM_VALUES_INVALID("dcql_query.credentials","DCQL claim values must be a non-empty array if claim values field is present."),
    DCQL_CREDENTIAL_SETS_REQUIRED("dcql_query.credentials","Each credential_set entry must contain options."),
    DCQL_CREDENTIAL_SETS_INVALID("dcql_query.credentials","DCQL credential_sets must be a non-empty array with non-empty values."),
    DCQL_DUPLICATE_CREDENTIAL_ID("dcql_query.credentials","Duplicate credential ids are not allowed."),
    DCQL_DUPLICATE_CLAIM_ID("dcql_query.credentials","Duplicate claim ids are not allowed."),
    DCQL_INVALID_CREDENTIAL_SET("dcql_query.credentials","credential_sets contains unknown credential id reference."),
    DCQL_INVALID_CLAIM_SET("dcql_query.credentials","claim_sets contains unknown claim id reference."),
    DCQL_MISSING_CLAIM_ID("dcql_query.credentials","claim_sets contains missing claim id reference."),
    DCQL_EMPTY_CLAIM_SET("dcql_query.credentials","claim_sets must not be empty if claim_sets field is present."),
    DCQL_CLAIM_PATH_INVALID("dcql_query.credentials","DCQL claim path must be a valid path."),
    DCQL_ALL_CREDENTIAL_SETS_OPTIONAL("dcql_query.credential_sets","credential_sets must contain at least one required entry."),
    CLIENT_ID_REQUIRED("invalid_request","client_id is required"),
    INVALID_RESPONSE_MODE("invalid_request", "responseMode must be direct_post or dc_api."),
    DC_API_REQUIRES_SIGNED_CLIENT_ID("invalid_request", "DC API response_mode requires a decentralized_identifier or x509_san_dns client_id."),
    VERIFIER_ORIGIN_REQUIRED("invalid_request", "Unable to determine verifier origin from Origin or Referer headers."),
    SUBMISSION_ORIGIN_NOT_ALLOWED("invalid_request", "Submission Origin is not in the authorization request expected_origins."),
    ORIGIN_AUDIENCE_VALIDATION_FAILED("invalid_request", "Origin audience validation failed due to invalid domain/aud."),
    DC_API_RESPONSE_CODE_NOT_SUPPORTED("invalid_request", "responseCodeValidationRequired is not supported with response_mode=dc_api."),
    INVALID_REQUEST_ID_MISSING("invalid_request", "requestId is required and cannot be empty."),
    CLIENT_ID_HOST_MISMATCH("invalid_request", "For the x509_san_dns client_id scheme, the DNS name in client_id must match this deployment's configured inji.verify.x509-san-dns.host."),
    CLIENT_ID_DNS_NAME_INVALID("invalid_request", "For the x509_san_dns client_id scheme, the value after the prefix must be a syntactically valid DNS name."),
    CLIENT_ID_REDIRECT_URI_INVALID("invalid_request", "For the redirect_uri client_id scheme, the value after the prefix must be a non-empty, well-formed absolute https URI."),
    CLIENT_ID_REDIRECT_URI_MISMATCH("invalid_request", "For the redirect_uri client_id scheme, the URI after the prefix must match this deployment's response_uri."),
    REQUEST_URI_INSECURE("invalid_request", "request_uri must be served over HTTPS outside local/dev environments for the x509_san_dns client_id scheme."),
    CLIENT_ID_CERTIFICATE_CHAIN_MISSING("invalid_request", "For the x509_san_dns client_id scheme, this deployment's keystore has no signing certificate chain configured."),
    NONCE_INVALID("invalid_request", "Nonce must contain only ASCII URL-safe characters (A-Z, a-z, 0-9, -, ., _, ~) and be at least 16 characters."),
    DID_CREATION_FAILED("DID_CREATION_FAILED","Error while creating DID document."),
    VP_SUBMISSION_EXCEPTION("VP_SUBMISSION_EXCEPTION","Error while processing VP submission"),
    TOKEN_MATCHING_FAILED("TOKEN_MATCHING_FAILED", "Token matching failed."),
    INVALID_VP_TOKEN("INVALID_VP_TOKEN","Verifiable Presentation Submission failed, due to invalid VP token"),
    VP_WITHOUT_PROOF("VP_WITHOUT_PROOF", "Invalid VP Submission since VP is without proof"),
    VP_VERIFICATION_FAILED("VP_VERIFICATION_FAILED", "VP verification failed due to runtime exception during VP verification"),
    RESPONSE_CODE_NOT_MATCHING("RESPONSE_CODE_NOT_MATCHING", "Response code is not matching the VP Submission response"),
    RESPONSE_CODE_EXPIRED("RESPONSE_CODE_EXPIRED", "Response code has expired"),
    RESPONSE_CODE_USED("RESPONSE_CODE_USED", "Response code has been used"),
    RESPONSE_CODE_NOT_FOUND("RESPONSE_CODE_NOT_FOUND", "Response code is missing for this VP Submission"),
    REDIRECT_URI_NOT_FOUND("REDIRECT_URI_NOT_FOUND", "Redirect URI configuration is missing"),
    VP_SESSION_INVALID("VP_SESSION_INVALID", "Your VP verification session is invalid. Please restart the process and try again"),
    MALFORMED_COOKIE("MALFORMED_COOKIE", "Request cannot be processed due to malformed cookie" ),
    RESPONSE_CODE_NOT_USED("RESPONSE_CODE_NOT_USED", "Transaction was incomplete, response_code was not used" ),
    NONCE_VALIDATION_FAILED("invalid_request", "Nonce validation failed due to invalid nonce/challenge."),
    CLIENT_ID_VALIDATION_FAILED("invalid_request", "Client id validation failed due to invalid client_id/domain."),
    CLIENT_ID_NONCE_VALIDATION_FAILED("invalid_request", "Client id or nonce validation failed"),
    INVALID_STATE_MISSING("invalid_request", "State parameter is required and cannot be empty."),
    NO_MATCHING_VP_REQUEST("invalid_request", "Invalid state parameter: No matching VP request found."),
    VP_REQUEST_EXPIRED("invalid_request", "Invalid state parameter: VP request has expired."),
    VP_ALREADY_SUBMITTED("invalid_request", "VP response has already been submitted."),
    EITHER_VP_TOKEN_OR_ERROR_REQUIRED("invalid_request", "Either vp_token or error must be provided."),
    BOTH_VP_TOKEN_AND_ERROR_NOT_ALLOWED("invalid_request", "Both vp_token and error cannot be provided together."),
    ERROR_DESCRIPTION_VP_TOKEN_CONFLICT("invalid_request", "If error_description is provided, vp_token must be null."),
    ERROR_DESCRIPTION_ERROR_REQUIRED("invalid_request", "If error_description is provided, error must also be provided."),
    VP_TOKEN_REQUIRED("invalid_request", "invalid_vp_token: vp_token is required and cannot be empty or 'null'"),
    DUPLICATE_QUERY_IDS_NOT_ALLOWED("invalid_request", "invalid_vp_token: duplicate query ids are not allowed"),
    VP_TOKEN_MUST_HAVE_KEY_VALUE_PAIR("invalid_request", "invalid_vp_token: must contain at least one key-value pair"),
    VP_TOKEN_VALUES_MUST_BE_ARRAYS("invalid_request", "invalid_vp_token: all values must be arrays"),
    VP_TOKEN_ARRAYS_MUST_HAVE_ELEMENTS("invalid_request", "invalid_vp_token: all arrays must have at least one element"),
    VP_TOKEN_ARRAY_ELEMENTS_INVALID("invalid_request", "invalid_vp_token: array elements must be non-empty JSON objects or non-empty SD-JWT strings"),
    VP_TOKEN_ALL_ELEMENTS_MUST_BE_OBJECTS("invalid_request", "invalid_vp_token: all elements must be non-empty JSON objects"),
    VP_TOKEN_ALL_ELEMENTS_MUST_BE_SD_JWT("invalid_request", "invalid_vp_token: all elements must be non-empty SD-JWT strings"),
    VP_TOKEN_NOT_VALID_JSON_OBJECT("invalid_request", "invalid_vp_token, not a valid JSON object"),
    VP_TOKEN_UNKNOWN_CREDENTIAL_ID("invalid_request", "vp_token contains credential id(s) not present in the DCQL query."),
    VP_TOKEN_MISSING_CREDENTIAL_ID("invalid_request", "vp_token is missing one or more required credential ids from the DCQL query."),
    VP_TOKEN_DCQL_NOT_SATISFIED("invalid_request", "vp_token does not satisfy the DCQL credential_sets requirements."),
    VP_TOKEN_CREDENTIAL_FORMAT_MISMATCH("invalid_request", "vp_token credential format does not match the format declared in the DCQL query."),
    VP_TOKEN_MULTIPLE_CREDENTIALS_NOT_ALLOWED("invalid_request", "vp_token contains multiple credentials for a query that does not allow multiple."),
    VP_TOKEN_EXPECTED_VERIFIABLE_PRESENTATION("invalid_request", "vp_token ldp_vc credential must be a VerifiablePresentation when require_cryptographic_holder_binding is true."),
    VP_TOKEN_EXPECTED_VERIFIABLE_CREDENTIAL("invalid_request", "vp_token ldp_vc credential must be a VerifiableCredential when require_cryptographic_holder_binding is false."),
    VP_TOKEN_MISSING_VERIFIABLE_CREDENTIAL("invalid_request", "vp_token VerifiablePresentation is missing a verifiableCredential array, which is required when require_cryptographic_holder_binding is true."),
    VP_TOKEN_SD_JWT_MISSING_CNF("invalid_request", "vp_token SD-JWT credential does not contain a cnf claim and therefore does not support Holder Binding, which is required when require_cryptographic_holder_binding is true."),
    VP_TOKEN_SD_JWT_MISSING_KEY_BINDING("invalid_request", "vp_token SD-JWT credential must include a Key Binding JWT when require_cryptographic_holder_binding is true."),
    VP_TOKEN_META_TYPE_VALUES_MISMATCH("invalid_request", "vp_token ldp_vc credential type values do not satisfy any of the type_values options in the DCQL query."),
    VP_TOKEN_SD_JWT_VCT_MISMATCH("invalid_request", "vp_token SD-JWT credential vct claim does not match any of the vct_values in the DCQL query."),
    VP_TOKEN_CLAIM_NOT_FOUND("invalid_request", "vp_token ldp_vc credential does not contain a required claim path declared in the DCQL query."),
    VP_TOKEN_CLAIM_VALUE_MISMATCH("invalid_request", "vp_token ldp_vc credential claim value does not match any of the declared values in the DCQL query."),
    VP_TOKEN_CLAIM_SETS_NOT_SATISFIED("invalid_request", "vp_token credential does not satisfy any of the claim_sets options declared in the DCQL query."),
    KB_JWT_IAT_MISSING_OR_INVALID("invalid_request", "KB-JWT iat claim is missing or invalid."),
    KB_JWT_IAT_IN_FUTURE("invalid_request", "KB-JWT iat is in the future beyond the allowed clock skew."),
    KB_JWT_IAT_TOO_OLD("invalid_request", "KB-JWT iat is too far in the past beyond the allowed max age."),
    UNKNOWN_PARAMETER("invalid_request", "Invalid parameter");

    private final String errorCode;
    private final String errorMessage;
}