import { ReactComponent as InjiLogo } from "../assets/images/inji-verify.svg";
import Outline from "../assets/scanner-outline.svg";
import { ReactComponent as GradientScanFillIcon } from "../assets/gradient-scan-icon.svg";
import { ReactComponent as WhiteScanFillIcon } from "../assets/white-scan-icon.svg";
import { ReactComponent as GradientTabUploadIcon } from "../assets/gradient-upload-icon.svg";
import { ReactComponent as WhiteTabUploadIcon } from "../assets/white-upload-icon.svg";
import { ReactComponent as QrCodeIcon } from "../assets/qr-code-icon.svg";
import { ReactComponent as CameraDeniedIcon } from "../assets/camera-access-denied-icon.svg";
import { ReactComponent as DocumentFileIcon } from "../assets/document.svg";
import { ReactComponent as VerificationSuccess } from "../assets/verification-success-icon.svg";
import { ReactComponent as VerificationFailed } from "../assets/verification-failed-icon.svg";
import { ReactComponent as GlobeSvgIcon } from "../assets/globe.svg";
import { ReactComponent as ArrowDownSvgIcon } from "../assets/arrow-down.svg";
import { ReactComponent as ArrowUpSvgIcon } from "../assets/arrow-up.svg";
import { ReactComponent as CheckSvgIcon } from "../assets/check.svg";


export const Logo = InjiLogo;
export const QrIcon = QrCodeIcon;
export const GradientScanIcon = GradientScanFillIcon;
export const WhiteScanIcon = WhiteScanFillIcon;
export const GradientUploadIcon = GradientTabUploadIcon;
export const WhiteUploadIcon = WhiteTabUploadIcon;
export const CameraAccessDeniedIcon = CameraDeniedIcon;
export const DocumentIcon = DocumentFileIcon;
export const VerificationSuccessIcon = VerificationSuccess;
export const VerificationFailedIcon = VerificationFailed;
export const ScanOutline = Outline;
export const GlobeIcon = GlobeSvgIcon;
export const ArrowDown = ArrowDownSvgIcon;
export const ArrowUp = ArrowUpSvgIcon;
export const Check = CheckSvgIcon;