version: '3.8'

services:
  inji-verify:
    image: mosipid/inji-verify:latest
    ports:
       - "3000:8000"
    environment:
      - INTERNET_CONNECTIVITY_CHECK_ENDPOINT=${INTERNET_CONNECTIVITY_CHECK_ENDPOINT-https://dns.google/}
      - INTERNET_CONNECTIVITY_CHECK_TIMEOUT=${INTERNET_CONNECTIVITY_CHECK_TIMEOUT-10000}
      - OVP_QR_HEADER={OVP_QR_HEADER-INJI_OVP://payload=}