name: tttyyBrowserStack Web Tests

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - '!release-branch'
      - release*
      - master
      - 1.*
      - develop
      - DSD*
    
jobs:
  inji-verify-test:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Maven 3.9.1
      run: |
        wget https://downloads.apache.org/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz
        tar -xzf apache-maven-3.9.1-bin.tar.gz
        sudo mv apache-maven-3.9.1 /usr/local/maven
        export M2_HOME=/usr/local/maven
        export PATH=${M2_HOME}/bin:${PATH}
        mvn -version    

    - name: Run tests
      run: |
         cd ui-test
         mvn clean test -DtestngXmlFile="TestNg.xml"

    - name: Save test reports
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-reports
        path: ui-test/test-output
